# Generated by Django 3.2 on 2021-05-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientbasicinfos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('checkdate', models.DateTimeField(auto_now=True, db_column='CheckDate', null=True)),
                ('checknumber', models.CharField(db_column='CheckNumber', max_length=15)),
                ('patientid', models.CharField(db_column='PatientID', max_length=15)),
                ('patientname', models.CharField(blank=True, db_column='PatientName', max_length=25, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=25, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=25, null=True)),
                ('clinicaldiagnosis', models.CharField(blank=True, db_column='ClinicalDiagnosis', max_length=4000, null=True)),
                ('examinationfindings', models.CharField(blank=True, db_column='ExaminationFindings', max_length=4000, null=True)),
                ('endoscopicdiagnosis', models.CharField(blank=True, db_column='EndoscopicDiagnosis', max_length=4000, null=True)),
                ('pathologicaldiagnosis', models.CharField(blank=True, db_column='PathologicalDiagnosis', max_length=4000, null=True)),
                ('patientreport', models.CharField(blank=True, db_column='PatientReport', max_length=255, null=True)),
                ('hospitalid', models.CharField(blank=True, db_column='HospitalID', max_length=3, null=True)),
            ],
            options={
                'db_table': 'patientbasicinfos',
                'managed': True,
            },
        ),
    ]
